apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-change.telegram: ""
spec:
  project: default
  source:
    repoURL: https://github.com/never3k/nginx-app.git
    path: apps/nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
